import { Student, UnionName } from './types';

export const UNIONS: UnionName[] = [
  "বসুরহাট পৌরসভা",
  "১নং সিরাজপুর ইউনিয়ন",
  "২নং চরপার্বতী ইউনিয়ন",
  "৩নং চরহাজারী ইউনিয়ন",
  "৪ নং চরকাঁকড়া ইউনিয়ন",
  "৫ নং চরফকিরা ইউনিয়ন",
  "৬ নং রামপুর ইউনিয়ন",
  "৭ নং মুছাপুর ইউনিয়ন",
  "৮ নং চরএলাহী ইউনিয়ন",
  "কবিরহাট পৌরসভা"
];

export const STUDENTS: Student[] = [
  {
    id: 1,
    name: "আব্দুল্লাহ আল নোমান",
    gender: "male",
    union: "৪ নং চরকাঁকড়া ইউনিয়ন",
    department: "ম্যানেজমেন্ট",
    session: "২১-২২",
    mobile: "01866899828",
    email: "308abdullahalnoman@gmail.com",
    villageWard: "চরকাঁকড়া ৮ নং ওয়ার্ড",
    highSchool: "পেশকারহাট উচ্চ বিদ্যালয়",
    college: "কোম্পানীগঞ্জ সরকারি কলেজ (সরকারি মুজিব কলেজ)",
    facebook: "facebook.com/abdullah.al.noman.642916"
  },
  {
    id: 2,
    name: "নাহিদ আলম",
    gender: "male",
    union: "৬ নং রামপুর ইউনিয়ন",
    department: "ইসলামের ইতিহাস ও সংস্কৃতি",
    session: "২৩-২৪",
    mobile: "01792101631",
    email: "nahidalomofficial279@gmail.com",
    villageWard: "রামপুর",
    highSchool: "তানযীমুল উম্মাহ",
    college: "তামীরুল মিল্লাত",
    facebook: "facebook.com/share/1Cs851VY3Q/"
  },
  {
    id: 3,
    name: "Fabiha Jannat Tisha",
    gender: "female",
    union: "বসুরহাট পৌরসভা",
    department: "Physics",
    session: "২০-২১",
    mobile: "01604895904",
    email: "tisha.cuphysics@gmail.com",
    villageWard: "Upoddilamchi",
    highSchool: "Basurhat A.H.C. Govt. High School",
    college: "Companigonj Govt. College",
    facebook: "facebook.com/share/1ABbNbHf2h/"
  },
  {
    id: 4,
    name: "Morsheda khanam Tamanna",
    gender: "female",
    union: "বসুরহাট পৌরসভা",
    department: "Islamic studies",
    session: "২০-২১",
    mobile: "01609761692",
    email: "mktamanna62@gmail.con",
    villageWard: "Karalia -3",
    highSchool: "BIFM",
    college: "BIFM",
    facebook: "facebook.com/share/14ScNBQXBCu/"
  },
  {
    id: 5,
    name: "আমেনা খাতুন অনন্যা",
    gender: "female",
    union: "৬ নং রামপুর ইউনিয়ন",
    department: "ক্রিমিনোলোজি এন্ড পুলিশ সাইন্স",
    session: "২৩-২৪",
    mobile: "01301632738",
    email: "anonnaamena@gmail",
    villageWard: "Rampur. Word no:07",
    highSchool: "Bamni Asiria Fazil Madrasha",
    college: "Bamni Asiria Fazil madrasha",
    facebook: "facebook.com/share/15S4t6thnfd/"
  },
  {
    id: 6,
    name: "মোহাম্মদ আবদুল মান্নান",
    gender: "male",
    union: "৬ নং রামপুর ইউনিয়ন",
    department: "শিক্ষা ও গবেষণা ইনস্টিটিউট",
    session: "২৪-২৫",
    mobile: "1310999857",
    email: "abdulmannantusu@gmail",
    villageWard: "রামপুর +০৮",
    highSchool: "বামনী আছিরিয়া ফাযিল মাদরাসা",
    college: "বামনী আছিরিয়া ফাযিল মাদরাসা",
    facebook: "facebook.com/share/1A17Mu2VnE/"
  },
  {
    id: 7,
    name: "Jahidul islam",
    gender: "male",
    union: "৫ নং চরফকিরা ইউনিয়ন",
    department: "Philosophy",
    session: "২১-২২",
    mobile: "01888666130",
    email: "rafijahid27@gmail.com",
    villageWard: "চরকালী ১ নং ওয়ার্ড",
    highSchool: "বসুরহাট ক্যাডেট মাদরাসা",
    college: "তামিরুল মিল্লাত কামিল মাদরাসা",
    facebook: "facebook.com/jahidul.islam.rafi.844445"
  },
  {
    id: 8,
    name: "নাজমুল হাসান",
    gender: "male",
    union: "৩নং চরহাজারী ইউনিয়ন",
    department: "পরিসংখ্যান",
    session: "১৮-১৯",
    mobile: "1835890748",
    email: "nazmulhasan19204045@gmail.com",
    villageWard: "চরহাজারী, ৭ নং ওয়ার্ড",
    highSchool: "আবু মাঝির হাট উচ্চ বিদ্যালয়",
    college: "কোম্পানীগঞ্জ সরকারি কলেজ(সরকারি মুজিব কলেজ)",
    facebook: "facebook.com/share/1BmcjZGY2b/"
  },
  {
    id: 9,
    name: "Asraful islam ontor",
    gender: "male",
    union: "৩নং চরহাজারী ইউনিয়ন",
    department: "Economics",
    session: "২৪-২৫",
    mobile: "01634349286",
    email: "asraful10ontor@gmail.com",
    villageWard: "Char hazari - word no.7",
    highSchool: "Abu mazirhat high school",
    college: "Government mujib college",
    facebook: "facebook.com/asraful.ontor.3"
  },
  {
    id: 10,
    name: "MUNTASIR FAHIM",
    gender: "male",
    union: "৩নং চরহাজারী ইউনিয়ন",
    department: "ECONOMICS",
    session: "১৮-১৯",
    mobile: "+1(929)428-9295",
    email: "mfthuserbabu095@gmail.com",
    villageWard: "CHARHAZARI, WARD-5",
    highSchool: "BASURHAT A.H.C GOVT. HIGH SCHOOL",
    college: "GOVT. MUJIB COLLEGE",
    facebook: "facebook.com/muntasirthuser095"
  },
  {
    id: 11,
    name: "আবদুর রহমান বাহাদুর",
    gender: "male",
    union: "৫ নং চরফকিরা ইউনিয়ন",
    department: "শিক্ষা ও গবেষণা ইনস্টিটিউট",
    session: "২৪-২৫",
    mobile: "01625444963",
    email: "mdkhanbahadur666712@gmail.com",
    villageWard: "চরকালী ৩ নং ওয়ার্ড",
    highSchool: "চাপরাশির হাট এ.রব ফাজিল মাদরাসা",
    college: "নোয়াখালী সরকারি কলেজ, নোয়াখালী",
    facebook: "facebook.com/share/17paayTaLw/"
  },
  {
    id: 12,
    name: "Mushfiqur Rahaman",
    gender: "male",
    union: "৭ নং মুছাপুর ইউনিয়ন",
    department: "fine arts",
    session: "২২-২৩",
    mobile: "01617085973",
    email: "mushfiqurrahaman362@gmail.com",
    villageWard: "musapur 6 no",
    highSchool: "Bamni High School",
    college: "Milestone College",
    facebook: "facebook.com/share/1JuifKc4yS/"
  },
  {
    id: 13,
    name: "Sabikun Nahar tonima",
    gender: "female",
    union: "১নং সিরাজপুর ইউনিয়ন",
    department: "International relations",
    session: "২৩-২৪",
    mobile: "01645352675",
    email: "lutfun1121@gmail.com",
    villageWard: "Mohammed nagar",
    highSchool: "Maqsudah govt. Girl's high school",
    college: "Govt. Mujib college",
    facebook: "facebook.com/share/17Bnm5WLbp/"
  },
  {
    id: 14,
    name: "Mahrabin Afrose Moumita",
    gender: "female",
    union: "বসুরহাট পৌরসভা",
    department: "Philosophy",
    session: "১৯-২০",
    mobile: "01768146598",
    email: "mahrebinmoumita99@gmail.com",
    villageWard: "Basurhat,ward no.3",
    highSchool: "Basurhat A.H.C government high school",
    college: "Government Mujib College",
    facebook: "facebook.com/share/17eeeiWAEG/"
  },
  {
    id: 15,
    name: "Muhammad Anas",
    gender: "male",
    union: "৩নং চরহাজারী ইউনিয়ন",
    department: "Arabic",
    session: "২১-২২",
    mobile: "01645143646",
    email: "muhammadanas3171@gmail.com",
    villageWard: "Charhazari+06",
    highSchool: "Hazarihat Alim Madrasah",
    college: "Bosurhar Islami Fazil Madrasah",
    facebook: "facebook.com/muhammad.anas.928336"
  },
  {
    id: 16,
    name: "Md Nohad",
    gender: "male",
    union: "৭ নং মুছাপুর ইউনিয়ন",
    department: "Arabic language and literature",
    session: "১৯-২০",
    mobile: "01868489154",
    email: "Ahmednohad33@gmail.com",
    villageWard: "Musapur + 2no word",
    highSchool: "Rangmala darussunnah Alim madrasah",
    college: "Tamirul millat kamil madrasah",
    facebook: "facebook.com/muhammad.anas.928336"
  },
  {
    id: 17,
    name: "Riya Chakraborty",
    gender: "female",
    union: "১নং সিরাজপুর ইউনিয়ন",
    department: "Fine Arts",
    session: "২২-২৩",
    mobile: "01873746775",
    email: "riyac6057@gmail.com",
    villageWard: "Birahimpur (3 No)",
    highSchool: "Jogidia Girls' High School",
    college: "Government Mujib College",
    facebook: "facebook.com/riya.chakraborty.579"
  },
  {
    id: 18,
    name: "তানভীর আহম্মেদ ছিদ্দিকী",
    gender: "male",
    union: "বসুরহাট পৌরসভা",
    department: "অর্থনীতি",
    session: "১৮-১৯",
    mobile: "01856822309",
    email: "tanviir048@gmail.com",
    villageWard: "৭নং ওয়ার্ড",
    highSchool: "বসুরহাট এ.এইচ.সি. সরকারি উচ্চ বিদ্যালয়",
    college: "নোয়াখালী সরকারি কলেজ",
    facebook: "facebook.com/share/1ZpJXou3op/"
  },
  {
    id: 19,
    name: "তারিফুল হাসান",
    gender: "male",
    union: "১নং সিরাজপুর ইউনিয়ন",
    department: "IER",
    session: "২২-২৩",
    mobile: "01852213220",
    email: "tarif305@gmail",
    villageWard: "শাহজাদপুর",
    highSchool: "বসুরহাট দারুল ইহসান মাদরাসা",
    college: "নটরডেম কলেজ",
    facebook: "facebook.com/share/1AGnVEWfCT/"
  },
  {
    id: 20,
    name: "Nahida Akter",
    gender: "female",
    union: "৪ নং চরকাঁকড়া ইউনিয়ন",
    department: "Management",
    session: "২১-২২",
    mobile: "01840454827",
    email: "nahidanishi0101@gmail.com",
    villageWard: "Charkakra, Ward no. 08",
    highSchool: "Maqsudah Govt. Girls' High School",
    college: "Government Mujib College",
    facebook: "facebook.com/share/1AeJoe1hoU/"
  },
  {
    id: 21,
    name: "আতাউর রহমান ফাহমিদ",
    gender: "male",
    union: "১নং সিরাজপুর ইউনিয়ন",
    department: "ইসলামিক স্টাডিজ",
    session: "১৯-২০",
    mobile: "01571306889",
    email: "arfahmid4@gmail.com",
    villageWard: "শাহজাদপুর, ৯নং ওয়ার্ড",
    highSchool: "জামেয়া ইসলামিয়া এমদাদিয়া দাখিল মাদ্রাসা",
    college: "টুমচর ইসলামিয়া কামিল মাদ্রাসা",
    facebook: "facebook.com/ataurrahman.fahmid.1"
  },
  {
    id: 22,
    name: "Masrurah hossain",
    gender: "female",
    union: "১নং সিরাজপুর ইউনিয়ন",
    department: "Environmental science",
    session: "২১-২২",
    mobile: "01614011578",
    email: "masrurah.hossain7@gmail.com",
    villageWard: "Mohammad nagar, word 2",
    highSchool: "Basurhat A.H.C. Govt. High School",
    college: "Govt. Hazi Mohammad Mohsin College",
    facebook: "facebook.com/share/17sERoGteT/"
  },
  {
    id: 23,
    name: "Salma",
    gender: "female",
    union: "৬ নং রামপুর ইউনিয়ন",
    department: "Public Administration",
    session: "২৩-২৪",
    mobile: "01601933608",
    email: "salma.alauddin04@gmail.com",
    villageWard: "Rampur",
    highSchool: "Dhanmondi Government Girl's High School, Dhaka",
    college: "BCIC College, Dhaka",
    facebook: "facebook.com/share/18367t3LnF/"
  },
  {
    id: 24,
    name: "Popy Rani Bhowmik",
    gender: "female",
    union: "৫ নং চরফকিরা ইউনিয়ন",
    department: "Sanskrit",
    session: "২০-২১",
    mobile: "01872911916",
    email: "bhowmikpopy2002@gmail.com",
    villageWard: "Charfakira,4 no",
    highSchool: "Kabi Jasim Uddin High School",
    college: "Govt.Mujib College",
    facebook: "facebook.com/share/1AGT2pf73A/"
  },
  {
    id: 25,
    name: "তানজিল ইসলাম তরুণ",
    gender: "male",
    union: "৪ নং চরকাঁকড়া ইউনিয়ন",
    department: "আরবি ভাষা ও সাহিত্য",
    session: "২০-২১",
    mobile: "01850517693",
    email: "torunkhan27@gmail.com",
    villageWard: "Peskarhat + 08",
    highSchool: "Mohammodia Islamia Dakhil Madrasha",
    college: "Tamirul Millat Kamal Madrasha",
    facebook: "facebook.com/share/1FNtPAu96F/"
  },
  {
    id: 26,
    name: "মাসউদুর রহমান ফাহাদ",
    gender: "male",
    union: "৪ নং চরকাঁকড়া ইউনিয়ন",
    department: "ইসলামিক স্টাডিজ",
    session: "১৯-২০",
    mobile: "01859167422",
    email: "mrafahad422@gmail.com",
    villageWard: "চরকাঁকড়া, ৫ নং ওয়ার্ড",
    highSchool: "পূর্ব চরকাঁকড়া সরকারি প্রাথমিক বিদ্যালয়, রংমালা দারুস সুন্নাহ মডেল আলিম মাদরাসা",
    college: "তা'মীরুল মিল্লাত কামিল মাদরাসা",
    facebook: "facebook.com/share/1DEavSaNFi/"
  },
  {
    id: 27,
    name: "Abdul Aziz Obi",
    gender: "male",
    union: "১নং সিরাজপুর ইউনিয়ন",
    department: "Microbiology",
    session: "২২-২৩",
    mobile: "01873746783",
    email: "azizobi210@gmail.com",
    villageWard: "Koraliya,3no word",
    highSchool: "Basurhat A.H.C Govt High School",
    college: "Government Laboratory High School",
    facebook: "facebook.com/share/17sJE5cAa2/"
  },
  {
    id: 28,
    name: "Tasnim Tarannum Raisha",
    gender: "female",
    union: "কবিরহাট পৌরসভা",
    department: "Soil science",
    session: "২২-২৩",
    mobile: "01610913444",
    email: "tarannumtasnim209@gmail.com",
    villageWard: "Purbofotejongopur, 4",
    highSchool: "Bashurhat Academy",
    college: "Noakhali Govt. Women's college",
    facebook: "facebook.com/share/17ygFRruU9/"
  },
  {
    id: 29,
    name: "Mariam binte nur",
    gender: "female",
    union: "বসুরহাট পৌরসভা",
    department: "Islamic history and culture",
    session: "২২-২৩",
    mobile: "01846124883",
    email: "mariammithila09@gmail.com",
    villageWard: "Bashurhat 9 no. Ward",
    highSchool: "Bushurhat Islamia Fazil Madrasah",
    college: "Feni Alia Madrasah",
    facebook: "facebook.com/share/1F6iiK7DMj/"
  },
  {
    id: 30,
    name: "Fatema Tur Zohura",
    gender: "female",
    union: "৪ নং চরকাঁকড়া ইউনিয়ন",
    department: "Mathematics",
    session: "২০-২১",
    mobile: "01309986734",
    email: "Zohurarimiremezohura@gmail.com",
    villageWard: "চরকাঁকড়া",
    highSchool: "Basurhat A.H.C Govt. High School",
    college: "Companigonj Govt. College",
    facebook: "Fatema Tur Zohura"
  },
  {
    id: 31,
    name: "Md.Zunawed Hosen Shanto",
    gender: "male",
    union: "৩নং চরহাজারী ইউনিয়ন",
    department: "Arabic",
    session: "২১-২২",
    mobile: "01821548510",
    email: "mdzunawed0185819@gmail.com",
    villageWard: "Chorhazari, 6 No",
    highSchool: "HM Islamia Kamil Madrasah",
    college: "Darunnajat Siddiqia Kamil Madrasah",
    facebook: "facebook.com/zh.santo.10"
  },
  {
    id: 32,
    name: "Joy Devnath",
    gender: "male",
    union: "৭ নং মুছাপুর ইউনিয়ন",
    department: "HRM",
    session: "২০-২১",
    mobile: "01876751817",
    email: "joydeb1817@gmail.com",
    villageWard: "Musapur, 03",
    highSchool: "Rongmala Ideal High School",
    college: "Kabi Nazrul Govt College",
    facebook: "facebook.com/share/17TixiSksU/"
  },
  {
    id: 33,
    name: "Md. Mezbah Uddin",
    gender: "male",
    union: "৬ নং রামপুর ইউনিয়ন",
    department: "Islamic History & Culture",
    session: "২৩-২৪",
    mobile: "01819735678",
    email: "mezbahuddin2024@gmail",
    villageWard: "রামপুর",
    highSchool: "বামনী আছিরিয়া ফাজিল মাদ্রাসা",
    college: "দারুন্নাজাতে সিদ্দিকীয়া কামিল মাদ্রাসা",
    facebook: "facebook.com/share/1BX9vWGtpb/"
  },
  {
    id: 34,
    name: "রফিকুল ইসলাম তারেক",
    gender: "male",
    union: "২নং চরপার্বতী ইউনিয়ন",
    department: "ফারসি ভাষা ও সাহিত্য",
    session: "২০-২১",
    mobile: "01815238793",
    email: "rafiqulislamtaareque@gmail.com",
    villageWard: "চরপার্বতী, ০৮",
    highSchool: "চরপার্বতী এস সি উচ্চ বিদ্যালয়",
    college: "সরকারি মুজিব কলেজ",
    facebook: "facebook.com/share/1Jt4e8XTB2/"
  },
  {
    id: 35,
    name: "জামিলাতুন নাওয়ার রুহী",
    gender: "female",
    union: "৭ নং মুছাপুর ইউনিয়ন",
    department: "মাইক্রোবায়োলজি",
    session: "২৪-২৫",
    mobile: "01827969682",
    email: "jamilatunnaowarruhi@gmail.com",
    villageWard: "মুছাপুর ৩ নং ওয়ার্ড",
    highSchool: "বসুরহাট এ এইচ সি সরকারি উচ্চ বিদ্যালয়",
    college: "বীরশ্রেষ্ঠ নূর মোহাম্মদ পাবলিক কলেজ",
    facebook: "facebook.com/share/17tQMGiA6A/"
  },
  {
    id: 36,
    name: "MD. ISRAFIL",
    gender: "male",
    union: "২নং চরপার্বতী ইউনিয়ন",
    department: "Arabic",
    session: "২১-২২",
    mobile: "01875829654",
    email: "md_israfil.cu@yahoo.com",
    villageWard: "Charparboti, 2no. Word",
    highSchool: "Hazarihat Alim Madrasah",
    college: "Ta'mirul Millat Kamil Madrasah",
    facebook: "facebook.com/mdisrafil.rubel.7"
  },
  {
    id: 37,
    name: "Musfiqa jannat",
    gender: "female",
    union: "বসুরহাট পৌরসভা",
    department: "Botany",
    session: "২১-২২",
    mobile: "01611866722",
    email: "Jmusfiqa@gmail.com",
    villageWard: "Karalia+ward no 3",
    highSchool: "Basurhat AHC govt. high school",
    college: "Birshrestha noor mohammad public college",
    facebook: "facebook.com/arnima.musfiqa"
  },
  {
    id: 38,
    name: "শহিদুল ইসলাম",
    gender: "male",
    union: "১নং সিরাজপুর ইউনিয়ন",
    department: "ইসলামিক স্টাডিজ",
    session: "২১-২২",
    mobile: "01882953906",
    email: "shahidul.islam.gnsbd@gmail.com",
    villageWard: "হাবিব পুর, ২ নং ওয়ার্ড",
    highSchool: "বসুরহাট ইসলামিয়া কামিল মাদ্রাসা",
    college: "আল জামেয়াতুল ফালাহিয়া কামিল মাদ্রাসা",
    facebook: "facebook.com/share/1FBfiyBABq/"
  },
  {
    id: 39,
    name: "Israt Jahan Jeny",
    gender: "female",
    union: "বসুরহাট পৌরসভা",
    department: "Physics",
    session: "২২-২৩",
    mobile: "01887530378",
    email: "isratjeny1445@gmail.com",
    villageWard: "Bijoybag, 2",
    highSchool: "Basurhat A.H.C Govt High School",
    college: "Noakhali Govt College",
    facebook: "facebook.com/share/1DL1NmVgso/"
  }
];